#!/usr/bin/env bash
#
#  vim:ft=sh:
#
#  Copyright (c) 2010-2017 Wael Nasreddine <wael.nasreddine@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
#  USA.
#

if [[ -z "${*}" ]]; then
  # we need the back and forth first
  echo back_and_forth
  # get a list of workspaces except for the one focused
  i3-msg -t get_workspaces | jq -r '.[] | if .focused == false then .name else empty end'
else
  # switch to the given workspace
  i3-msg workspace "${@}" >/dev/null
fi
