# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "amazon-ecr-credential-helper-unstable-${version}";
  version = "2018-05-25";
  rev = "95a58a5bf07c045cbd5377c3dac2a21dc2cd8656";

  goPackagePath = "github.com/awslabs/amazon-ecr-credential-helper";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/awslabs/amazon-ecr-credential-helper";
    sha256 = "0mpwm21fphg117ryxda7696s8bnvi4bbc8rvi4zp2m1rhl04j2yy";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
