{
  imports = [
    ./nixos/general/editor.nix
    ./nixos/general/keyboard.nix
    ./nixos/general/nixpkgs.nix
    ./nixos/general/home-manager.nix
    ./nixos/general/users.nix
    ./nixos/general/version.nix
    ./nixos/general/security.nix
    ./nixos/general/location.nix
    ./nixos/general/nix.nix
    ./nixos/hardware/serial_console.nix
    ./nixos/hardware/precision-7530.nix
    ./nixos/hardware/thinkpad-e580.nix
    ./nixos/hardware/machine.nix
    ./nixos/hardware/fwupd.nix
    ./nixos/hardware/intel_backlight.nix
    ./nixos/hardware/hetzner_sb36.nix
    ./nixos/hardware/zeus.nix
    ./nixos/hardware/hetzner_cloud.nix
    ./nixos/hardware/thinkpad-p1.nix
    ./nixos/hardware/hetzner_sb53.nix
    ./nixos/hardware/xps-13.nix
    ./nixos/services/plex.nix
    ./nixos/services/docker.nix
    ./nixos/services/printers.nix
    ./nixos/services/libvirt.nix
    ./nixos/services/ssh.nix
    ./nixos/software/neovim.nix
    ./nixos/software/tmux.nix
    ./nixos/software/zsh.nix
    ./nixos/software/general.nix
    ./nixos/software/curl.nix
    ./nixos/workstation/bluetooth.nix
    ./nixos/workstation/gtk.nix
    ./nixos/workstation/power.nix
    ./nixos/workstation/teamviewer.nix
    ./nixos/workstation/keeptruckin.nix
    ./nixos/workstation/networking.nix
    ./nixos/workstation/yubikey.nix
    ./nixos/workstation/xorg.nix
    ./nixos/workstation/fonts.nix
    ./nixos/workstation/sound.nix
    ./nixos/workstation/virtualbox.nix
    ./nixos/workstation/autorandr.nix
    ./nixos/workstation/gnome-keyring.nix
    ./nixos/workstation/redshift.nix
  ];
}
