# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "swm-unstable-${version}";
  version = "2018-07-27";
  rev = "b0ba0d9bf880f1c2e6bb4503b9a14062d499ecbf";

  goPackagePath = "github.com/kalbasit/swm";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/kalbasit/swm";
    sha256 = "1dxxq6a2hf67gq578kzd9795vaslpddym00lia3vp1rf0z8kvb99";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
