#!/bin/bash

# Get the project name
project_name="$(wingo-cmd 'Input "Project name:"')"

# Create a new workspace and switch to it
wingo-cmd "Workspace (AddWorkspace \"${project_name}\")"

# Start an emacs
wingo-cmd "Shell \"named-emacs-frame ${project_name}\""

# Start a shell
wingo-cmd "Shell \"urxvt -name ${project_name}\""
