#!/usr/bin/env bash
set -ex

if [[ $# -ne 1 ]]; then
  echo "USAGE: $0 </Applications/*/Contents/SharedSupport/InstallESD.dmg>"
  exit 1
fi

# Mount the installer image
hdiutil attach "$1" -noverify -nobrowse -mountpoint /Volumes/install_app

# Create El Capitan sparseimage of 7316mb with a Single Partition - Apple Partition Map
hdiutil create -o /tmp/OSXInstall -size 7316m -layout SPUD -fs HFS+J -type SPARSE

# Mount the El Capitan sparseimage
hdiutil attach /tmp/OSXInstall.sparseimage -noverify -nobrowse -mountpoint /Volumes/install_build

# Restore the Base System into the El Capitan Blank sparseimage
asr restore -source /Volumes/install_app/BaseSystem.dmg -target /Volumes/install_build -noprompt -noverify -erase

# Remove Packages link and replace with actual files
rm /Volumes/OS\ X\ Base\ System/System/Installation/Packages
cp -rp /Volumes/install_app/Packages /Volumes/OS\ X\ Base\ System/System/Installation/

# Copy El Capitan installer dependencies
cp -rp /Volumes/install_app/BaseSystem.chunklist /Volumes/OS\ X\ Base\ System/BaseSystem.chunklist
cp -rp /Volumes/install_app/BaseSystem.dmg /Volumes/OS\ X\ Base\ System/BaseSystem.dmg

# Unmount the installer image
hdiutil detach /Volumes/install_app

# Unmount the Base System image
hdiutil detach /Volumes/OS\ X\ Base\ System/

# Optimise Sparseimage Size
hdiutil compact /tmp/OSXInstall.sparseimage
hdiutil resize -size min /tmp/OSXInstall.sparseimage

# Convert the OSXInstall spareseimage to ISO/CD master
hdiutil convert /tmp/OSXInstall.sparseimage -format UDTO -o /tmp/OSXInstall.iso

# Rename the OSXInstall ISO image and move it to the desktop
mv /tmp/OSXInstall.iso.cdr ~/Desktop/OSXinstall.iso

# Delete OSXInstall.sparseimage file
rm -f /tmp/OSXInstall.sparseimage
