#!/usr/bin/env bash
#
#   vim:ft=sh:fenc=UTF-8:ts=4:sts=4:sw=4:expandtab:foldmethod=marker:foldlevel=0:
#
#   $Id: cs 789 2008-03-24 13:02:06Z wael $
#
#   Copyright (c) 2007 Wael Nasreddine <wael.nasreddine@gmail.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
#   USA.
#

set -e

# Bootstrap{{{
bootstrap="$( dirname "${0}" )/.bootstrap"
if [ -f "${bootstrap}" ]; then
    # shellcheck disable=1090
    source "${bootstrap}"
else
    echo "Cannot bootstrap"
    exit 54
fi
unset bootstrap
#}}}

start_editor="true"
if [[ "${1}" = "--no-editor" ]]; then
    start_editor="false"
    shift
fi

if [ "${#}" -ne "1" ]; then
    print_error 0 "Usage: ${0} [--no-editor] <script_name>"
    exit 1
fi

cd "$( dirname "${0}" )"
if [ ! -f "${1}" ]; then
    cp .tmpl "${1}"
    chmod +x "${1}"
fi

[[ "${start_editor}" = "true" ]] && $EDITOR "${1}"
