#!/usr/bin/env bash
#
# vim:foldmethod=marker:foldlevel=0:
#
# Copyright (c) 2014-2017 Wael Nasreddine <wael.nasreddine@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Bootstrap{{{
bootstrap="$( dirname "${0}" )/.bootstrap"
if [ -f "${bootstrap}" ]; then
  # shellcheck disable=1090
  source "${bootstrap}"
else
  echo "Cannot bootstrap"
  exit 54
fi
unset bootstrap
#}}}
# Main {{{
start_editor="true"
if [[ "${1}" = "--no-editor" ]]; then
  start_editor="false"
  shift
fi

if [ "${#}" -ne "1" ]; then
  print_error 0 "Usage: ${0} [--no-editor] <script_name>"
  exit 1
fi

cd "$( dirname "${0}" )" || exit 1
if [[ ! -f "${1}" ]]; then
  cp .tmpl "${1}"
  chmod +x "${1}"
fi

[[ "${start_editor}" = "true" ]] && $EDITOR "${1}"
# }}}
