#!/usr/bin/env python

from __future__ import print_function
from optparse import OptionParser
import os
import sys
import tempfile

parser = OptionParser()

parser.add_option("-i", "--import", dest="imports", action="append", default=[],
                  help="Import package of given name", metavar="PACKAGE")

parser.add_option("-p", "--package", dest="package", action="store_false", default=True,
                  help="Specify 'package main' (enabled by default)")

parser.add_option("-m", "--main", dest="main", action="store_true", default=True,
                  help="Wrap input in a main func (enabled by default)")

parser.add_option("-d", "--debug", dest="debug", action="store_true", default=False,
                  help="Print the generated Go code instead of running it.")

(options, args) = parser.parse_args()

stdin = ""
for line in sys.stdin.readlines():
    stdin += "%s\n" % line

out = ""
if options.package:
    out += "package main\n\n"

for package in options.imports:
    out += "import \"%s\"\n" % package

out += "\n"
if options.main:
    out += "func main() {\n%s\n}\n" % stdin
else:
    out += stdin

if options.debug:
    print(out)
else:
    _, temp_file_path = tempfile.mkstemp(".go")
    temp_file_handler = open(temp_file_path, 'w')
    print(out, file=temp_file_handler)
    temp_file_handler.close()
    os.execlp("go", "", "run", temp_file_path)
    os.unlink(temp_file_path)
