#!/bin/bash
# Originally submitted on Super User by evsmith at the address
# http://superuser.com/a/888245/29825

set -e

if [[ -t 0 ]]; then
  pids=(${@})
else
  read -ra pids
fi

for pid in "${pids[@]}"; do
  if [[ -f "/proc/${pid}/smaps" ]]; then
    echo "* Mem usage for PID $pid"
    rss=$(awk 'BEGIN {i=0} /^Rss/ {i = i + $2} END {print i}' "/proc/${pid}/smaps")
    pss=$(awk 'BEGIN {i=0} /^Pss/ {i = i + $2 + 0.5} END {print i}' "/proc/${pid}/smaps")
    sc=$(awk 'BEGIN {i=0} /^Shared_Clean/ {i = i + $2} END {print i}' "/proc/${pid}/smaps")
    sd=$(awk 'BEGIN {i=0} /^Shared_Dirty/ {i = i + $2} END {print i}' "/proc/${pid}/smaps")
    pc=$(awk 'BEGIN {i=0} /^Private_Clean/ {i = i + $2} END {print i}' "/proc/${pid}/smaps")
    pd=$(awk 'BEGIN {i=0} /^Private_Dirty/ {i = i + $2} END {print i}' "/proc/${pid}/smaps")
    echo "-- Rss: $rss kB"
    echo "-- Pss: $pss kB"
    echo "Shared Clean $sc kB"
    echo "Shared Dirty $sd kB"
    echo "Private $(( pd + pc )) kB"
  fi
done
