#!/bin/bash

case `hostname -f` in
  *.roam.*)
    CONFIG_FILE="${HOME}/.i3/laptop_status.conf"
    ;;
  *)
    CONFIG_FILE="${HOME}/.i3/desktop_status.conf"
    ;;
esac

i3status --config "${CONFIG_FILE}"
