#!/usr/bin/env bash
#
# vim:foldmethod=marker:foldlevel=0:
#
# Copyright (c) 2014-2017 Wael Nasreddine <wael.nasreddine@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

set -e

# How many days should we keep the messages?
EXPIRATION=30

# remove the expiring flag from messages that has been redeemed
notmuch tag -expiring -- tag:expiring and not tag:deleted and not tag:spam

for day in $(seq 0 $((EXPIRATION - 1))); do
  nextday="$(( day + 1 ))"
  # remove the expire flag for those redeemed
  notmuch tag "-expire-${day}" "-expire-${nextday}" -- '(' "tag:expire-${day}" or "tag:expire-${nextday}" ')' and not tag:expiring
  # move the expire flag by -1 for those that are still flagged
  notmuch tag "+expire-${day}" "-expire-${nextday}" -- "tag:expire-${nextday}" and tag:expiring
done

notmuch tag +expire-$EXPIRATION +expiring -- '(' tag:deleted or tag:spam ')' and not tag:expiring

# Delete all the expiring messages that has been deleted for 30 days if any
if [[ "$(notmuch count --exclude=false tag:expire-0 and tag:expiring)" -gt 0 ]]; then
  notmuch search --format=text0 --exclude=false --output=files tag:expire-0 and tag:expiring | xargs -0 rm
  notmuch new --no-hooks
fi
