#!/usr/bin/env bash
#
# vim:foldmethod=marker:foldlevel=0:
#
# Copyright (c) 2014-2017 Wael Nasreddine <wael.nasreddine@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

set -e

if [[ "${1}" = "--profile" ]]; then
  profile="${2}"
  shift 2
fi

if [[ -z "${profile}" ]]; then
  items="personal\npublica\ntalentoday"
  profile=$(rofi -dmenu < <(echo -e "${items}"))
fi

case "${profile}" in
  personal)
    (exec chromium --user-data-dir="${HOME}/.config/chromium-personal" "${@}" &>/dev/null)&
    ;;
  publica)
    (exec chromium --user-data-dir="${HOME}/.config/chromium-publica" "${@}" &>/dev/null)&
    ;;
  talentoday)
    (exec chromium --user-data-dir="${HOME}/.config/chromium-talentoday" "${@}" &>/dev/null)&
    ;;
  *)
    echo -e "${profile} is not recognized"
    ;;
esac
