#!/bin/bash

if [[ $# -ne 3 ]]; then
  echo "USAGE: $0 <pro|org> <repo> <branch>"
  exit 1
fi

TYPE="${1}"
REPO="${2}"
BRANCH="${3}"

if [[ "x${TYPE}" = "xpro" ]]; then
  pro="--pro"
else
  pro=""
fi

BUILD_NUMBER="`travis branches ${pro} --repo "${REPO}" 2>/dev/null| grep "^${BRANCH}:" | awk '{print $2}' | cut -d\# -f2`"
if [[ -z "${BUILD_NUMBER}" ]]; then
  echo "unable to parse the build number"
  exit 1
fi

travis restart "${BUILD_NUMBER}" ${pro} --repo "${REPO}"
