#!/usr/bin/env bash
#
# vim:foldmethod=marker:foldlevel=0:
#
# Copyright (c) 2014-2017 Wael Nasreddine <wael.nasreddine@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

handle_interrupt () {
    echo -e "${FG_RED_B}Aborting...${FG_CLEAR}"
    rm -f "${LOCK}" "${TMP}" "${FILE}"
    exit 130
}

### Traping Control C
trap handle_interrupt 2 15

if [ -z "${EDITOR}" ]; then
    echo -e "${FG_RED_B}ERROR: EDITOR is not defined, cannot continue...${FG_CLEAR}"
    exit 1
fi

LOCK="/tmp/rmjunk.lock"
if [ -f "${LOCK}" ]; then
    echo -e "${FG_RED_B}rmjunk is already in use,${FG_CLEAR}"
    echo -e "${FG_BLUE_B}If not then please remove ${LOCK} and try again.${CLEAR}"
    exit 1
fi
touch ${LOCK}


TMP="$(mktemp /tmp/rmjunk.XXXXXXX)"
FILE="$(mktemp /tmp/rmjunk.XXXXXXX)"

# Put the header in the file, preparing to fill it
echo "=== Files to remove (you may delete items from it) ===" > "${FILE}"

# Find all junkie files in $@ or /
find "${@-.}" \
    \( -name "*~" -type f \) \
    -o \( -name "*.pacorig" -type f \) \
    -o \( -name "*.pacnew" -type f \) \
    -o \( -name "*.pacsave" -type f \) \
    -o \( -name "*.orig" -type f \) \
    -o \( -name "*.rej" -type f \) \
    >> "${TMP}" 2> /dev/null

# Sorting/filtering all the files into ${FILE}
# Remove non-writable files.
for i in $(uniq "${TMP}" | sort); do
    if [ -w "${i}" ]; then
        echo "${i}" >> "${FILE}"
    fi
done

# Launching the editor so the user can remove
# Files from the rm command
echo -e "${FG_BLUE_B}Launching editor...${FG_CLEAR}"
"${EDITOR}" "${FILE}"

# Removing files
files=($(grep -v "=== Files to remove (you may delete items from it) ===" "${FILE}"))
rm -f "${files[@]}"

# Remove temporary files and lock file
rm -f "${FILE}" "${TMP}" "${LOCK}"
