#!/bin/bash

set -e

# Forget any currently running agent
unset SSH_AUTH_SOCK SSH_AGENT_PID

# The shell to which we tailor export/setent statements.
USER_SHELL=$1

# setup the initial pssh to use current SSH_AGENT_NAME or ACTIVE_PROFILE
pssh() {
  export SSH_AGENT_NAME="${SSH_AGENT_NAME:-${ACTIVE_PROFILE}}"
}

# Source the active profile so it overloads the pssh
if [[ -n "${ACTIVE_PROFILE}" ]] && [[ -r "${HOME}/.zsh/profiles/${ACTIVE_PROFILE}" ]]; then
  # shellcheck disable=SC1090
  source "${HOME}/.zsh/profiles/${ACTIVE_PROFILE}"
fi

# call pssh to setup SSH_AGENT_NAME
pssh

# no SSH_AGENT_NAME? exit
if [[ -z "${SSH_AGENT_NAME}" ]]; then
  exit 0
fi

# Path where we store the ssh-agent environment variables, so that
# multiple sessions may look for an existing agent.
SSH_AGENT_FILE="{$HOME}/.ssh/${SSH_AGENT_NAME}/agent"
if [[ ! -w "$( dirname "${SSH_AGENT_FILE}" )" ]]; then
  exit # do not spawn an agent if we cannot write to $HOME.
fi

function start_ssh_agent() {
  # No. Try to get the environment variables from the file.
  if [[ -f "${SSH_AGENT_FILE}" ]] ; then
    eval "$( grep -v echo "${SSH_AGENT_FILE}" )"
  fi

  # Exit status of ssh-add
  #   0 means the agent exists and has keys,
  #   1 means the agent exists but has no keys, and
  #   2 means agent does not exist.
  ssh-add -l > /dev/null 2>&1
  agent_status=$?

  # Does our environment point to an agent now?
  if [ $agent_status -eq 2 ]; then
    # No.  Start an ssh-agent, saving the environment variables.
    if ssh-agent -s > "${SSH_AGENT_FILE}"; then
      echo "Failed to start the ssh-agent." >&2
      return
    fi
    eval "$( grep -v echo "${SSH_AGENT_FILE}" )"
  fi

  # Add all of the keys
  for key in $(find "${HOME}/.ssh/${SSH_AGENT_NAME}/" -not -name '*.pub' -not -name agent -type f | sed -e 's://:/:g'); do
    ssh-add "${key}" < /dev/null > /dev/null 2>&1
  done
}


function export_env() {
  # Print commands to setup environment.  This handles tcsh and
  # assumes everyone else can understand sh syntax (bash, ksh, zsh
  # and maybe others).  Other folks can add detection for more
  # esoteric shells as needed.

  for var in "${@}" ; do
    if [[ -n "${!var}" ]] ; then
      if [ "${USER_SHELL##*/}" = "tcsh" ] ; then
        echo "setenv $var ${!var};"
      elif [ "${USER_SHELL##*/}" = "fish" ] ; then
        echo "set -Ux $var ${!var};"
      else
        echo "$var=${!var}; export $var;"
      fi
    fi
  done
}

start_ssh_agent
export_env SSH_AUTH_SOCK SSH_AGENT_PID
