#!/bin/bash
dir=`mktemp -d`
trap "rm -r $dir" 0
cat "$@" > "$dir"/msg
if munpack -C "$dir" -t < "$dir"/msg 2>&1 | grep 'Did not find'; then
    sed -n '/[Hh][Tt][Mm][Ll]/,$p' "$dir"/msg > $dir/part1.html
    rm "$dir"/msg
fi
for i in "$dir"/part*; do
    if grep -q -i -e '<html>' -e 'text/html' "$i"; then
        x-www-browser "$i" &
        sleep 3
        exit 0
    fi
done
