#!/bin/bash

case `hostname -f` in
  *.roam.*)
    sink=1 ;;
  *)
    sink=0 ;;
esac

case "${1}" in
  down)
    pactl set-sink-volume $sink -- -10% ;;
  up)
    pactl set-sink-volume $sink -- +10% ;;
  toggle)
    pactl set-sink-mute $sink toggle ;;
esac
