[
  ./generic/keyboard.nix
  ./generic/nixos.nix
  ./generic/nixpkgs.nix
  ./generic/non-nixos.nix
  ./services/gnupg.nix
  ./services/lowbatt.nix
  ./services/weechat.nix
  ./software/fzf.nix
  ./software/git.nix
  ./software/hammerspoon/default.nix
  ./software/htop.nix
  ./software/keybase.nix
  ./software/less.nix
  ./software/neovim.nix
  ./software/nodejs.nix
  ./software/packages.nix
  ./software/pet.nix
  ./software/ssh.nix
  ./software/syncthing.nix
  ./software/taskwarrior.nix
  ./software/tmux.nix
  ./software/zsh/default.nix
  ./theme/default.nix
  ./theme/gruvbox/default.nix
  ./theme/seoul256-dark/default.nix
  ./workstation/alacritty/default.nix
  ./workstation/autorandr.nix
  ./workstation/bluetooth.nix
  ./workstation/default.nix
  ./workstation/dropbox.nix
  ./workstation/dunst.nix
  ./workstation/email.nix
  ./workstation/firefox.nix
  ./workstation/greenclip.nix
  ./workstation/gtk.nix
  ./workstation/i3/bar/default.nix
  ./workstation/i3/default.nix
  ./workstation/locker.nix
  ./workstation/mysql-workbench.nix
  ./workstation/rofi/default.nix
  ./workstation/termite.nix
  ./workstation/urxvt.nix
  ./workstation/window-manager.nix
]
