#!/bin/bash
#
# Copyright (C) 2006 Kolesnikov Vova

if [ $1 ]
then ratmenu \
-back ~/.ratmenu/player \
-label Volume \
down "mpc volume -10;~/.ratmenu/volume 1;" \
up "mpc volume +10;~/.ratmenu/volume;"
else ratmenu \
-back ~/.ratmenu/player \
-label volume \
up "mpc volume +10;~/.ratmenu/volume;" \
down "mpc volume -10;~/.ratmenu/volume 1"
fi
