#!/bin/zsh

#CPU_MODEL=$(grep -m1 '^model name' /proc/cpuinfo | cut -d : -f 2)
#case "$CPU_MODEL" in
#        *Opteron*)    export CPU_CFLAGS="-mtune=opteron"   ;;
#        *Pentrium*M)  export CPU_CFLAGS="-mtune=pentium-m" ;;
#	*)            export CPU_CLFAGS=""                 ;;
#esac
#export CFLAGS="$CPU_CFLAGS -O2 -g -Wall"
#export CXXFLAGS="$CFLAGS"

#export DISTCC_HOSTS="xenon/4 electron/4 meson/1 localhost"

# --- ccache ---

CCACHE_BIN_DIR=/usr/lib/ccache
MY_CCACHE_DIR=/ccache

if [ -d /usr/lib/ccache/ ] && ( echo $PATH | grep -v -q "$CCACHE_BIN_DIR" ) ; then
        export PATH=$CCACHE_BIN_DIR:$PATH
fi

if [ -L ${MY_CCACHE_DIR} ] ; then
        MY_CCACHE_DIR=$(readlink ${MY_CCACHE_DIR} 2>/dev/null)
fi

if [ -d ${MY_CCACHE_DIR} ] && [ -w ${MY_CCACHE_DIR} ] ; then
       export CCACHE_DIR=${MY_CCACHE_DIR}
fi
