#!/bin/zsh

# add edit command line feature ("alt-e")
autoload      edit-command-line
zle -N        edit-command-line
bindkey '\ee' edit-command-line

cd()
{
    if builtin cd "$@"; then
        if [ -x "$(${W} devtodo 2> /dev/null)" ]; then
            devtodo ${TODO_OPTIONS}
        fi
    fi
}

pushd()
{
    if builtin pushd "$@"; then
        if [ -x "$(${W} devtodo 2> /dev/null)"]; then
            devtodo ${TODO_OPTIONS}
        fi
    fi
}

popd()
{
    if builtin popd "$@"; then
        if [ -x "$(${W} devtodo 2> /dev/null)"]; then
            devtodo ${TODO_OPTIONS}
        fi
    fi
}

# reload zshrc
function src()
{
    autoload -U compinit zrecompile

    compinit -d $zsh_cache/zcomp-$HOST

    for f in $HOME/.zshrc $zsh_cache/zcomp-$HOST; do
        zrecompile -p $f && rm -f $f.zwc.old
    done

    source ~/.zshrc
}
