# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/BurntSushi/xgb";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/xgb";
      rev = "27f122750802c950b2c869a5b63dafcf590ced95";
      sha256 = "18lp2x8f5bljvlz0r7xn744f0c9rywjsb9ifiszqqdcpwhsa0kvj";
    };
  }
  {
    goPackagePath = "github.com/BurntSushi/xgbutil";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/xgbutil";
      rev = "f7c97cef3b4e6c88280a5a7091c3314e815ca243";
      sha256 = "0kw0zmpbnymnalpj2wsvxbb7p5c297kv0qhyj20mcwg8dz64drnp";
    };
  }
  {
    goPackagePath = "github.com/google/go-github";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-github";
      rev = "c0b63e2f9bb198baf328c8abf1ddcbe05ff9427e";
      sha256 = "1a4skdbzxnyj3irqrmhhj4c9cimga0k5sd0vykjfqj7c8c5bwbd5";
    };
  }
  {
    goPackagePath = "github.com/google/go-querystring";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-querystring";
      rev = "53e6ce116135b80d037921a7fdd5138cf32d7a8a";
      sha256 = "0lkbm067nhmxk66pyjx59d77dbjjzwyi43gdvzyx2f8m1942rq7f";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "ce7b0b5c7b45a81508558cd1dba6bb1e4ddb51bb";
      sha256 = "0lc39b6xrxv7h3v3y1kgz49cgi5qxwlygs715aam6ba35m48yi7g";
    };
  }
  {
    goPackagePath = "github.com/olekukonko/tablewriter";
    fetch = {
      type = "git";
      url = "https://github.com/olekukonko/tablewriter";
      rev = "d4647c9c7a84d847478d890b816b7d8b62b0b279";
      sha256 = "1274k5r9ardh1f6gsmadxmdds7zy8rkr55fb9swvnm0vazr3y01l";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "816c9085562cd7ee03e7f8188a1cfd942858cded";
      sha256 = "1ws5crb7c70wdicavl6qr4g03nn6m92zd6wwp9n2ygz5c8rmxh8k";
    };
  }
  {
    goPackagePath = "github.com/rs/zerolog";
    fetch = {
      type = "git";
      url = "https://github.com/rs/zerolog";
      rev = "9cd6f6eef2d7e9041629e2dd853778a9b2abddbd";
      sha256 = "1bpqizv3h6dfawi5c3nckhicjbb9x0rfyl6rvgr4li2wa4nx1f68";
    };
  }
  {
    goPackagePath = "github.com/spf13/afero";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/afero";
      rev = "787d034dfe70e44075ccc060d346146ef53270ad";
      sha256 = "0138rjiacl71h7kvhzinviwvy6qa2m6rflpv9lgqv15hnjvhwvg1";
    };
  }
  {
    goPackagePath = "go.i3wm.org/i3";
    fetch = {
      type = "git";
      url = "https://github.com/i3/go-i3";
      rev = "ca7db01cbb323ab7c5476f602c894d3b6aab4506";
      sha256 = "1qisavhbirzha56h2dzq4xvwgww34hx52k68ml8732mazgjgwcxc";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "a680a1efc54dd51c040b3b5ce4939ea3cf2ea0d1";
      sha256 = "018zmn4kmg2mbngcciqal54slc3pl4ry5vlv0bw36fcxvnazxnbp";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "ef147856a6ddbb60760db74283d2424e98c87bff";
      sha256 = "1q1vm1z40fx1grlrm7az4rln6v5pj9xi5n1cjqg5xgq4dsk9132y";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "0605a8320aceb4207a5fb3521281e17ec2075476";
      sha256 = "1pak7q9ivwxh5bnjk00pkrs9ri9vmbyccvza56fl6138w397h49j";
    };
  }
  {
    goPackagePath = "gopkg.in/urfave/cli.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/urfave/cli.v2";
      rev = "d3ae77c26ac8db90639677e4831a728d33c36111";
      sha256 = "0fcw39hkwq4dn7n2m4gc4p66hb8h6c2161ah15iy2g45iypzpfkb";
    };
  }
]
