#!/bin/bash
set -e

# simplified pathprepend used for early X
function _pathprepend() {
  if [[ -d "${1}" ]] && ! [[ $PATH =~ (^|:)$1($|:) ]]; then
    PATH="$1:$PATH"
  fi
}

# simplified pathappend used for early X
function _pathappend() {
  if [[ -d "${1}" ]] && ! [[ $PATH =~ (^|:)$1($|:) ]]; then
    PATH="$PATH:$1"
  fi
}

# initialize the PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin"

# Important variable
export BROWSER="${HOME}/.bin/relay-browser"
export EDITOR="nvim"
export LANG=en_US.UTF-8
export LC_ALL="${LANG}"
export MYFS="${HOME}/.local"
export SUDO_EDITOR="nvim"
export TERM=termite

# add my bin folders to the PATH
_pathprepend "${HOME}/.bin"
_pathprepend "${HOME}/code/bin"
_pathprepend "${MYFS}/bin"
if [[ -d "${MYFS}/opt" ]]; then
  for dir in ${MYFS}/opt/*/bin; do
    _pathappend "${dir}"
  done
fi
if [[ -d "${HOME}/.libexec" ]]; then
  for dir in ${HOME}/.libexec/*; do
    _pathappend "${dir}"
  done
fi

# make java applications look decent
export _JAVA_AWT_WM_NONREPARENTING=1

# sway-specific setting
export XKB_DEFAULT_OPTIONS=ctrl:nocaps
export WLC_REPEAT_DELAY=200
export WLC_REPEAT_RATE=30
export XKB_DEFAULT_VARIANT=colemak
# export GTK_IM_MOUDLE=ibus
# export XMODIFIERS=@im=ibus
# export QT_IM_MODULE=ibus

unset -f _pathprepend
unset -f _pathappend

sway 2> ~/.sway.log
