[
  ./general/editor.nix
  ./general/keyboard.nix
  ./general/nixpkgs.nix
  ./general/home-manager.nix
  ./general/users.nix
  ./general/version.nix
  ./general/security.nix
  ./general/location.nix
  ./general/nix.nix
  ./hardware/serial_console.nix
  ./hardware/precision-7530.nix
  ./hardware/thinkpad-e580.nix
  ./hardware/machine.nix
  ./hardware/fwupd.nix
  ./hardware/intel_backlight.nix
  ./hardware/hetzner_sb36.nix
  ./hardware/zeus.nix
  ./hardware/hetzner_cloud.nix
  ./hardware/thinkpad-p1.nix
  ./hardware/hetzner_sb53.nix
  ./hardware/xps-13.nix
  ./services/plex.nix
  ./services/docker.nix
  ./services/printers.nix
  ./services/libvirt.nix
  ./services/ssh.nix
  ./software/neovim.nix
  ./software/tmux.nix
  ./software/zsh.nix
  ./software/general.nix
  ./software/curl.nix
  ./workstation/bluetooth.nix
  ./workstation/gtk.nix
  ./workstation/power.nix
  ./workstation/teamviewer.nix
  ./workstation/keeptruckin.nix
  ./workstation/networking.nix
  ./workstation/yubikey.nix
  ./workstation/xorg.nix
  ./workstation/fonts.nix
  ./workstation/sound.nix
  ./workstation/virtualbox.nix
  ./workstation/autorandr.nix
  ./workstation/gnome-keyring.nix
  ./workstation/redshift.nix
]
