# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "pet-unstable-${version}";
  version = "2018-06-14";
  rev = "e2b42ac4c7067ae474d54a16054b840848c11d85";

  goPackagePath = "github.com/knqyf263/pet";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/knqyf263/pet";
    sha256 = "1zv2jfgh5nqd4cwr1ljm5p4rqam7hq3a6asfmhr3lcnp7sz9b8fr";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
