# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    cryptkey = {
      device = "/dev/disk/by-uuid/4d340cea-b271-4540-88ba-d57829622e38";
    };

    cryptroot = {
      device = "/dev/disk/by-uuid/3da97a3e-98bc-4947-83a9-5c7647db3150";
      keyFile = "/dev/mapper/cryptkey";
    };

    cryptswap = {
      device = "/dev/disk/by-uuid/9c521d99-67b5-4b77-b6d2-ee152ccad85b";
      keyFile = "/dev/mapper/cryptkey";
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/de2f32b1-85d0-49ab-8684-019175e09544";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/02EA-F418";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/de2f32b1-85d0-49ab-8684-019175e09544";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@home" ];
    };

  fileSystems."/nix-store" =
    { device = "/dev/disk/by-uuid/de2f32b1-85d0-49ab-8684-019175e09544";
      fsType = "btrfs";
      options = [ "subvol=@nixos/@nix-store" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/be829e9b-e163-45fb-beea-aa4cf1aa6012"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
